# -*- coding: utf-8 -*-
"""Cats And DogsClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z0PHxwfH3kPZKNoRZGUSoBZmZekTiawN
"""

import os
import cv2 
import random as r
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten,Conv2D,MaxPool2D,Dropout

# Taking Cats and Dogs images from Drive
cats = os.listdir('/content/drive/My Drive/datasets/cats_dogs/cats')
dogs = os.listdir('/content/drive/My Drive/datasets/cats_dogs/dogs')
len(cats),len(dogs) # Checking length

# Storing Images in A list
c = []
for i in cats:
  try:
    a =  cv2.imread(f'/content/drive/My Drive/datasets/cats_dogs/cats/{i}')
    b = cv2.cvtColor(a,cv2.COLOR_BGR2RGB)
    # img = cv2.resize(cv2.cvtColor(img2,cv2.COLOR_RGB2GRAY),(256,256))
    c.append(b)
  except(Exception) as e:
    print(e)

d = []
for i in dogs:
  try:
    a =  cv2.imread(f'/content/drive/My Drive/datasets/cats_dogs/dogs/{i}')
    b = cv2.cvtColor(a,cv2.COLOR_BGR2RGB)
    # img = cv2.resize(cv2.cvtColor(img2,cv2.COLOR_RGB2GRAY),(256,256))
    d.append(b)
  except(Exception) as e:
    print(e)

# Plotting Original Images
plt.figure(figsize=(10,8))
plt.suptitle('Before Resize...', size = 20)
for i in range(0,16) :
    plt.subplot(4,4,i+1)
    j = r.randint(0,len(c))
    plt.axis('off')
    # plt.tight_layout()
    plt.imshow(c[j])

plt.figure(figsize=(10,8))
plt.suptitle('Before Resize...', size = 20)
for i in range(0,16) :
    plt.subplot(4,4,i+1)
    j = r.randint(0,len(d))
    plt.axis('off')
    # plt.tight_layout()
    plt.imshow(d[j])

# Resizing and storing Cats and Dogs images in a list

cat_data = []
dog_data = []
for i in cats:
  try:
    img1 =  cv2.imread(f'/content/drive/My Drive/datasets/cats_dogs/cats/{i}')
    img2 = cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)
    img = cv2.resize(cv2.cvtColor(img2,cv2.COLOR_RGB2GRAY),(256,256))
    cat_data.append(img)
  except(Exception) as e:
    print(e)

for i in dogs:
  try:
    img1 =  cv2.imread(f'/content/drive/My Drive/datasets/cats_dogs/dogs/{i}')
    img2 = cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)
    img = cv2.resize(cv2.cvtColor(img2,cv2.COLOR_RGB2GRAY),(256,256))
    dog_data.append(img)
  except(Exception) as e:
    print(e)

# Plotting After Resize
plt.figure(figsize=(8,8))
plt.suptitle('After Resize and GrayScale', size = 20)
for i in range(0,16) :
    plt.subplot(4,4,i+1)
    j = r.randint(0,len(cat_data))
    plt.axis('off')
    # plt.tight_layout()
    plt.imshow(cat_data[j])

plt.figure(figsize=(8,8))
plt.suptitle('After Resize and GrayScale', size = 20)
for i in range(0,16) :
    plt.subplot(4,4,i+1)
    j = r.randint(0,len(dog_data))
    plt.axis('off')
    # plt.tight_layout()
    plt.imshow(dog_data[j])

# cat_data
# dog_data
len(cat_data),len(dog_data)

# adding label value to images
cat_lab = list(zip(cat_data,[0 for x in range(len(cat_data))]))
dog_lab = list(zip(dog_data,[1 for x in range(len(dog_data))]))

cat_lab[1:5],dog_lab[1:5]

data = []
data.extend(cat_lab)
data.extend(dog_lab)
r.shuffle(data) # shuffling the Data
len(data)
# data

# Dividing Data into Train,Test and validation
train_fea = []
train_lab = []

valid_fea = []
valid_lab = []

test_fea = []
test_lab = []

for i in range(int(2023*0.75)): # taking 75% Data for traing
  train_fea.append(data[i][0])
  train_lab.append(data[i][1])
for j in range(int(2023*0.75),int(2023*0.75)+int(2023*0.05)): # taking 5% Data for validation
  valid_fea.append(data[j][0])
  valid_lab.append(data[j][1])
for k in range(int(2023*0.75)+int(2023*0.05),2023): # taking 20% Data for Testing
  test_fea.append(data[k][0])
  test_lab.append(data[k][1])

print('train_fea :',len(train_fea))
print('train_lab :',len(train_lab))
print('valid_fea :',len(valid_fea))
print('valid_lab :',len(valid_lab))
print('test_fea :',len(test_fea))
print('test_lab :',len(test_lab))

# Coverting Into Numpy Arrays

train_fea = np.array(train_fea)
train_lab = np.array(train_lab)

valid_fea = np.array(valid_fea)
valid_lab = np.array(valid_lab)

test_fea = np.array(test_fea)
test_lab = np.array(test_lab)

train_fea.shape

# reshaping features
train_fea = train_fea.reshape((train_fea.shape[0],256,256,1))
valid_fea = valid_fea.reshape((valid_fea.shape[0],256,256,1))
test_fea = test_fea.reshape((test_fea.shape[0],256,256,1))

train_fea.shape

# Creating Model

'''model = Sequential()
model.add(Conv2D(24,(3,3), input_shape = (180,180,1)))
model.add(MaxPool2D(2,2))
model.add(Conv2D(24,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(24,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))
model.add(Flatten())
model.add(Dense(24,activation='relu'))
model.add(Dense(2,activation='softmax'))'''

model = Sequential([Conv2D(64,(3,3), input_shape = (256,256,1)),
                    MaxPool2D(2,2),
                    Conv2D(64,(3,3),activation='relu'),
                    MaxPool2D(2,2),
                    Conv2D(64,(3,3),activation='relu'),
                    MaxPool2D(2,2),
                    Flatten(),
                    Dense(64,activation='relu'),
                    Dense(2,activation='softmax')])
model.summary()

#Compiling
model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])

epoch = model.fit(train_fea,train_lab,epochs=20,batch_size = 40,validation_data=(valid_fea,valid_lab),verbose=1)

# Evaluating the Model
model.evaluate(test_fea,test_lab,verbose = 1)

history = epoch.history

#Plotting the Loss & Val_Loss , Accuracy & Val_Accuracy
plt.figure(figsize = (15,5)),
plt.subplot(1,2,1)
plt.plot(history['loss'], color = 'r')
plt.plot(history['val_loss'], color = 'g')
plt.title('Loss and Val_Loss', size = 15,color = 'orange')
plt.legend(['Loss','Val_Loss']) 

plt.subplot(1,2,2)
plt.plot(history['accuracy'], color = 'r')
plt.plot(history['val_accuracy'], color = 'g')
plt.title('Accuracy and Val_Accuracy', size = 15, color = 'orange')
plt.tight_layout()
plt.legend(['Accuracy','Val_Accuracy'])
plt.show()

# Plotting Predicted Output with Image
plt.figure(figsize = (8,8))
for i in range(0,16):
  plt.subplot(4,4,i+1)
  j = r.randint(0,len(test_fea))
  change = test_fea[j].reshape(1,256,256,1)
  pre1 = model.predict(change)
  img = change.reshape(256,256)
  # img1 = cv2.cvtColor(img,cv2.COLOR_GRAY2RGB)
  # image = cv2.cvtColor(img1,cv2.COLOR_RGB2BGR)
  def x():
    if np.argmax(pre1)==0:
      return 'Cat',round(pre1.max()*100)
    else:
      return  'Dog',round(pre1.max()*100)
  plt.imshow(img)
  plt.axis('off')
  plt.title(x(),size = 10)

